# Prometheus/Grafana stack configuration
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
    retention: "15d"
  
grafana:
  enabled: true
  adminPassword: "admin123"
  persistence:
    enabled: true
    size: 10Gi
  service:
    type: LoadBalancer
  
alertManager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 2Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true